apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-todo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: node-todo
  template:
    metadata:
      labels:
        app: node-todo
    spec:
      containers:
      - image: index.docker.io/arey/springboot-petclinic:latest
        name: node-todo
        ports:
        - containerPort: 8080
