apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-node-server
  template:
    metadata:
      labels:
        app: test-node-server
    spec:
      containers:
      # modify the following line with your Docker Hub account name
      - image: qkdlql/test-node-server:v1
        name: test-node-server
        ports:
        - containerPort: 8090
